---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-inferencegraph-distro-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - kserve-inferencegraph-auth-verifiers
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - get
