# Important: this is cluster and hardware dependent
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-p2-policy
  namespace: openshift-sriov-network-operator
spec:
  deviceType: netdevice
  isRdma: true
  linkType: eth
  mtu: 9000
  nicSelector:
    deviceID: 101d
    rootDevices:
      - 0000:5c:00.0
      - 0000:5c:00.1
    pfNames:
      - p2
    vendor: 15b3
  nodeSelector:
    feature.node.kubernetes.io/pci-15b3.present: 'true'
    feature.node.kubernetes.io/pci-15b3.sriov.capable: 'true'
    feature.node.kubernetes.io/rdma.available: 'true'
    feature.node.kubernetes.io/rdma.capable: 'true'
  numVfs: 8
  priority: 98
  resourceName: p2rdma
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: roce-p2
  namespace: openshift-sriov-network-operator
spec:
  ipam: |-
    {
      "type": "whereabouts",
      "range": "10.0.128.0/21",
      "exclude" : [
          "10.0.128.0/22"
      ],
      "routes": [
        { "dst": "10.100.0.0/16", "gw": "10.0.128.1" },
        { "dst": "10.200.0.0/16", "gw": "10.0.128.1" },
        { "dst": "10.101.0.0/16", "gw": "10.0.128.2" },
        { "dst": "10.200.0.0/16", "gw": "10.0.128.2" }
      ]
    }
  logLevel: info
  networkNamespace: 'llm-test'
  resourceName: p2rdma
  spoofChk: "off"
  trust: "on"
