# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:0b0dd6f4ee311854a6b8e18b3bc52e7aa6b66f935a16c8f9bda173353ab16c64 AS builder
ENV PATH="$PATH:/opt/app-root/src/go/bin"

# These built-in args are defined in the global scope, and are not automatically accessible within build stages or RUN commands.
# To expose these arguments inside the build stage, we need to redefine it without a value.
ARG TARGETOS TARGETARCH
RUN echo "GOOS=${TARGETOS} GOARCH=${TARGETARCH}"

USER root
WORKDIR /go/src/github.com/opendatahub-io/kserve-module
COPY kserve-module/go.mod  go.mod
COPY kserve-module/go.sum  go.sum
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY kserve-module/cmd/kserve-module/ cmd/kserve-module/
COPY kserve-module/pkg/              pkg/
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOFLAGS=-mod=readonly GOEXPERIMENT=strictfipsruntime  go build -tags strictfipsruntime -a -o manager ./cmd/kserve-module

# Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:17fd831ced9434de0a984d60b3fbe61008308261ba98bbc348d6fbdef05fa7c0
RUN microdnf install -y shadow-utils && \
    microdnf clean all && \
    useradd kserve -m -u 1000 && \
    microdnf remove -y shadow-utils
COPY --from=builder /go/src/github.com/opendatahub-io/kserve-module/manager /manager
COPY kserve-module/prefetched-manifests-rhoai /opt/manifests-template/
COPY config/ /opt/manifests-template/kserve/
USER 1000:1000
ENTRYPOINT ["/manager"]
