# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.26@sha256:890b54e8d329f33f094ab17881bd37e20b80a54cc39141637310911d8dd9c575 AS builder
ENV PATH="$PATH:/opt/app-root/src/go/bin"

# These built-in args are defined in the global scope, and are not automatically accessible within build stages or RUN commands.
# To expose these arguments inside the build stage, we need to redefine it without a value.
ARG TARGETOS TARGETARCH
RUN echo "GOOS=${TARGETOS} GOARCH=${TARGETARCH}"

USER root
WORKDIR /go/src/github.com/opendatahub-io/kserve-module
COPY kserve-module/go.mod  go.mod
COPY kserve-module/go.sum  go.sum
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY kserve-module/cmd/kserve-module/ cmd/kserve-module/
COPY kserve-module/pkg/              pkg/
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOFLAGS=-mod=readonly GOEXPERIMENT=strictfipsruntime  go build -tags strictfipsruntime -a -o manager ./cmd/kserve-module

# Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:5ed244b62bbf4095080144d9d35eb8fcd3d39a9801f94aadd63b9d10978a01ae
RUN microdnf install -y shadow-utils && \
    microdnf clean all && \
    useradd kserve -m -u 1000 && \
    microdnf remove -y shadow-utils
COPY --from=builder /go/src/github.com/opendatahub-io/kserve-module/manager /manager
COPY kserve-module/prefetched-manifests-rhoai /opt/manifests-template/
COPY config/ /opt/manifests-template/kserve/
USER 1000:1000
ENTRYPOINT ["/manager"]
