[project]
requires-python = ">=3.11,<3.13"
dependencies = [
    "kserve",
    "kserve-storage",
    "autogluon.common==1.5.0+rhaiv.5",
    "autogluon.core==1.5.0+rhaiv.5",
    "autogluon.features==1.5.0+rhaiv.5",
    "autogluon.tabular[lightgbm,xgboost,tabm,fastai]==1.5.0+rhaiv.5",
    "autogluon.timeseries==1.5.0+rhaiv.5",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
rhoai-build = ["setuptools>=61.0", "wheel"]

[tool.uv.sources]
"autogluon.common" = { index = "aipcc" }
"autogluon.core" = { index = "aipcc" }
"autogluon.features" = { index = "aipcc" }
"autogluon.tabular" = { index = "aipcc" }
"autogluon.timeseries" = { index = "aipcc" }

[[tool.uv.index]]
name = "aipcc"
url = "https://console.redhat.com/api/pypi/public-rhai/rhoai/3.5/cpu-ubi9/simple/"
default = true
