apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/kserve?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "build/operator-nudging.yaml"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request"
      && target_branch == "rhoai-2.24-wznoinsktest"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: wznoinsktest
    appstudio.openshift.io/component: odh-kserve-storage-initializer-v2-24-wznoinsktest
    pipelines.appstudio.openshift.io/type: build
  name: odh-kserve-storage-initializer-v2-24-on-pull-request-wznoinsktest
  namespace: wznoinsk-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/ppc64le
    - linux/s390x
    - linux-m2xlarge/arm64
  - name: dockerfile
    value: Dockerfiles/storage-initializer.Dockerfile.konflux
  - name: path-context
    value: python
  - name: hermetic
    value: false
  - name: build-image-index
    value: true
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/konflux-central.git
    - name: revision
      value: '{{ target_branch }}'
    - name: pathInRepo
      value: pipelines/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-kserve-storage-initializer-v2-24
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
