name: Validation

on:
  pull_request:
  push:

jobs:
  validate-manifests:
    name: Validate Kustomize manifests
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-validate-manifests
      cancel-in-progress: true

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5

    - name: Install kustomize
      run: |
        set -euo pipefail
        curl -fsSL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 5.7.1
        sudo mv kustomize /usr/local/bin/

    - name: Validate Kustomize manifests
      run: |
        # Exclude development overlays and dev-image-config overlays
        # Certain files are .gitignored and will cause the validation to fail
        set -euo pipefail
        ./hack/validate-manifests.sh \
          --ignore config/overlays/development \
          --ignore config/overlays/dev-image-config \
          --ignore test/overlays/istio
